name: 依赖安全检查

# 仅在 Pull Request 时运行
on:
  pull_request:
    branches:
      - master
      - develop

# 设置权限
permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: 依赖审查
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 依赖审查
        uses: actions/dependency-review-action@v4
        with:
          # 失败阈值：critical, high, moderate, low
          fail-on-severity: high
          # 检查许可证
          license-check: true
          # 允许的许可证列表
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD

