name: 测试 SSH 连接

on:
  workflow_dispatch:

jobs:
  test-connection:
    name: 测试服务器连接
    runs-on: ubuntu-latest
    
    steps:
      - name: 测试端口连通性
        run: |
          echo "测试 SSH 端口..."
          nc -zv -w5 ${{ secrets.SERVER_HOST }} ${{ secrets.SERVER_PORT }} || echo "端口无法连接"
      
      - name: 测试 SSH 登录（密码）
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "✅ SSH 连接成功！"
            echo "当前用户: $(whoami)"
            echo "系统信息: $(uname -a)"
            echo "当前目录: $(pwd)"
            echo "SSH 配置:"
            grep -E "^(Port|PasswordAuth|PubkeyAuth|PermitRoot)" /etc/ssh/sshd_config

